# root = 'simple-crack/dataset'
train_dir = 'simple-crack/dataset/train'
val_dir = 'simple-crack/dataset/valid'
test_dir = 'simple-crack/dataset/test'
# predict_dir = 'simple-crack/dataset/predict'
target_size = [224, 224]
batch_size = 32
class_mode = 'binary'
